### ISSUE TITLE
Plans to port it over to .NET Core 3?

### ISSUE THREAD

**Issue by gtsmagic** [jamesseanwright/personality-forge-.net#1]
Hi James, and thank you for the wonderful work you did on this library. I noticed you are targeting .NET Framework 4.6.1 - 4.7.2. According to Microsoft going forward .NET 5 will essentially be running on the .NET Core Code base instead. 

Do you have any plans to port the project over? If so can I be of assistance to you to expedite this process? 

Thanks,
Pete

**Comment by gtsmagic** [comment]
Update on this, I had some free time so I gave the porting a try. Seems to be working fine. You can see it here: 

https://github.com/gtsmagic/PersonalityForgeCore

I called it PersonalityForgeCore so that the two don't get mistaken for each other. I didn't write any test cases or anything, but would love the chance to work with you to do some bug fixes and finish it up. 

Let me know if you are interested. 

Thanks,
Pete

**Comment by jamesseanwright** [comment]
Hey @gtsmagic,

Thanks for reaching out; I'm glad to see you were able to port my work over to .NET Core with minimal friction.

I originally built this project to practise my C# chops. Given I haven't touched it in years, and it was mostly something I wrote as a junior developer, I'm not really interested in pursuing it further.

Thanks for your time nonetheless,
James
